services:
  # finances:
  #   image: ${DOCKER_REGISTRY-}finances
  #   build:
  #     context: .
  #     dockerfile: FinancesApp_Api/Dockerfile
  #   ports:
  #     - "1410:8080"
  #   depends_on:
  #     - db
  #     - redis
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1470:1433"
    environment:
      SA_PASSWORD: "Numsey@Password!"
      ACCEPT_EULA: "Y"
  
  redis:
    image: redis:latest
    ports:
      - "1405:6379"
 
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./logs:/logs:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
